### ISSUE TITLE
Use 'alpine' as a base image

### ISSUE THREAD

**Issue by utdemir** [utdemir/ghc-musl#1]
Using alpine as a base image makes it easier to install extra libraries, and results on a more normal-looking image.

Discussion at: https://www.reddit.com/r/haskell/comments/e79ts9/ann_docker_images_with_ghcmusl_for/f9wxlre?utm_source=share&utm_medium=web2x

**Comment by SandiCat** [comment]
This would be very handy. Having to use nix to add libraries defeats the purpose of using this instead of https://github.com/nh2/static-haskell-nix

**Comment by utdemir** [comment]
Update: i'm currently working on this on `alpine-base` branch.

**Comment by utdemir** [comment]
This is proved to be a bit difficult for me since it was hard to get Nix and apk installed tools play well together. I'd appreciate some help if someone has more experience and time.

**Comment by utdemir** [comment]
This is probably not going to happen (unless someone sends a PR :) ). See https://gitlab.com/neosimsim/docker-builder-images if you want musl-compiled GHC's without Nix.

**Comment by utdemir** [comment]
@SandiCat just wanted to let you know that I just replaced Nix with Alpine; now the library can be extended with usual Docker mechanisms.
