### ISSUE TITLE
Update image to GHC 9.0.2

### ISSUE THREAD

**Issue by sproott** [utdemir/ghc-musl#18]
Since 2022-01-10, Stackage nightly has switched from GHC 9.0.1 to 9.0.2. Because of this, ghc-musl builds with Stack are capped to nightly-2022-01-06, the last version using GHC 9.0.1.

**Comment by utdemir** [comment]
Thanks @sproott ! I just released `v23` with `GHC 9.0.2`. Let me know if it works for you!

**Comment by sproott** [comment]
It works nicely, thanks.

I have a problem though. I'm trying to build a `monomer` app and I'm getting linker errors:

![image](https://user-images.githubusercontent.com/46423131/154289452-c8d3c603-f1ba-4d90-9b3e-d4b7b300c8e9.png)

I think I have the required dependencies (sdl2-dev and glew-dev), but the linker fails anyways. Any ideas on what to do? 

EDIT:

I have found a few packages which probably contain the libraries I need - `libx11-dev`, `glu` and `mesa-dev`.

EDIT 2:

I get the exact same errors even after installing the packages. The libraries are actually located in `/usr/lib` as they should be:

![image](https://user-images.githubusercontent.com/46423131/154295125-b484c965-6f38-49b6-8048-4b100a347300.png)

Still, the linker does not find them.

**Comment by utdemir** [comment]
This is interesting. If you could provide an example cabal project I can try to get it build (or even add it to the test cases).

**Comment by sproott** [comment]
Sure, here it is: https://github.com/sproott/monomer-static-build-problem. Everything is set up in the Dockerfile (including the Stack commands), so it's enough to just run `docker build .`.

**Comment by sproott** [comment]
I also posted an issue to the `monomer` issue tracker, in case it's a `monomer` problem. https://github.com/fjvallarino/monomer/issues/85

**Comment by sproott** [comment]
Also, I'm pretty sure this has happened even with the previous version (9.0.1), so maybe I should move this into a new issue?

**Comment by utdemir** [comment]
Thanks for all your work!

> maybe I should move this into a new issue?

I'm fine either way :). Either a new issue or renaming the title of this issue would be fine.

---

About the issue, I'll only be able to have a look at the example repository a week from now. Meanwhile, feel free to update issue/send a PR if you make progress :).

**Comment by sproott** [comment]
Alright, here's a new issue: https://github.com/utdemir/ghc-musl/issues/19

I'm closing this then, the 9.0.2 image works, so it's resolved.
