### ISSUE TITLE
Docker image with GHC 9.2.5

### ISSUE THREAD

**Issue by lolepezy** [utdemir/ghc-musl#34]
Hi,

[I'm using ghc-musl docker image](https://github.com/lolepezy/rpki-prover/blob/master/Dockerfile.static-builder) to create a builder image on top of it and then use it with `stack`. I am trying to switch from GHC 8.10.7 to 9.2 which currently means using LTS 20.6 bundled with GHC 9.2.5. 

Would it be possible to push `utdemir/ghc-musl:v24-ghc925`? I only see v24-ghc922 on the Dockerhub. Or what is your policy about image versions?

I am also okay with building `ghc-musl:v24-ghc925` myself locally, but I'm not very familiar with Earthly and not sure how to do it. If I run `earthly --allow-privileged --push --artifact +ghc925/README` the image is apparently built, but is not pushed or something. So what would be the easier way to get a 9.2.5-based image pushed to the local Docker?

**Comment by utdemir** [comment]
Hey, thanks for opening the issue!

I just pushed a new version that includes GHC 9.2.5: utdemir/ghc-musl:v25-ghc925

Although I was the one pushing it, the credit for work goes to @TravisCardwell. I hope it will solve your issue.

> okay with building ghc-musl:v24-ghc925 myself locally,

I guess the above would be easier for you, but for reference, if you'd like to build the image, you should be able to do something like:

```
earthly --allow-privileged +ghc925 
```

which would add the image to your local Docker image registry.

---

I'm closing the issue, but please feel free to reopen this if it doesn't fix your issue :).

**Comment by lolepezy** [comment]
> I just pushed a new version that includes GHC 9.2.5: utdemir/ghc-musl:v25-ghc925

Thanks! That works for me.
