### ISSUE TITLE
adding pcre

### ISSUE THREAD

**Issue by amesgen** [utdemir/ghc-musl#8]
pcre-light has a few [reverse dependencies](https://packdeps.haskellers.com/reverse/pcre-light) (in particular lens-regex-pcre), so it would be nice if `pcre` was part of the containers.

Thanks for this very useful project!

**Comment by utdemir** [comment]
Thanks @amasgen. I'll add the `pcre` C library this weekend, then `pcre` stuff from Hackage should work.

**Comment by utdemir** [comment]
I just released `v12` which contains `pcre`. Let me know if that doesn't work for you!

Thanks again.
