### ISSUE TITLE
add bz2 & openssl

### ISSUE THREAD

**Issue by amesgen** [utdemir/ghc-musl#9]
- bzip2 (via `bzlib-conduit`, which is a dependency of `zip`)
 - openssl 1.1.1 (via `HsOpenSSL`, which is a dependency of `http-client-openssl`). This one is not that important, as one can use `http-client-tls` in most cases.

I think this should be it for my use case, but feel free to not include something if you consider it to be bloaty.

**Comment by utdemir** [comment]
Both sound good to me. I'll add them in a few days.

**Comment by utdemir** [comment]
I added `openssl` and `bzip2` libraries and released `v13`. Let me know if they work out for you!

**Comment by amesgen** [comment]
Yeah, works perfectly! :+1:
